baseURL = 'https://jaredstewart.io/'
languageCode = 'en-us'
title = 'Fragments of a System'
subtitle = 'the personal blog of jared stewart'

theme = 'typo'

# SEO and Performance
enableRobotsTXT = true
enableGitInfo = true

# RSS and Sitemap
[sitemap]
changefreq = 'whenever'
filename = 'sitemap.xml'
priority = 0.5

[taxonomies]
tag = 'tags'

[params]
# Site subtitle
subtitle = "the personal blog of jared stewart"

# Meta description
description = "Personal blog of Jared Stewart - software engineer, technical leader, and builder of scalable systems. Insights on technology, leadership, and problem-solving."

# SEO Keywords
keywords = ["software engineer", "technical leadership", "scalable systems", "engineering management", "full-stack development"]

# Author information for SEO
author = "Jared Stewart"

# Open Graph defaults
[params.opengraph]
type = "website"
locale = "en_US"

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = false
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/jaredandrewstewart/"


[[params.social]]
name = "github"
url = "https://github.com/JaredStewart"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "blog"
url = "/blog"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
